
const images = {
    Activity_Icon: require('./img/activity.png'),
Aadhaar_Card: require('./img/aadhaar-card.png'),
Back_Arrow: require('./img/back_arrow.png'),
Camera_Icon: require('./img/camera_icon.png'),
Cross_Icon: require('./img/cross.png'),
Dashboard_rectangle: require('./img/Dashboard_rectangle.png'),
Dropdown_Arrow: require('./img/dropdown_back_arrow.png'),
Download_icon: require('./img/download_icon.png'),
Delete_icon: require('./img/delete_icon.png'),
Delete_icon1: require('./img/delete_icon1.png'),
Employees_Icon: require('./img/employees.png'),
Edit_Icon: require('./img/edit_icon.png'),
Edit_Icon1: require('./img/edit_icon1.png'),
Forward_Arrow: require('./img/forward_arrow.png'),
Group_Users: require('./img/group_users.png'),
Gallery_Icon: require('./img/gallery_icon.png'),
Home: require('./img/Home.png'),
Ledger: require('./img/Wallet.png'),
Notification: require('./img/notifications.png'),
OpenEye_ICON: require('./img/open_eye.png'),
ClosedEye_ICON: require('./img/closed_eye.png'),
Profile: require('./img/Profile.png'),
Products_Icon: require('./img/Products_Icon.png'),
Profile_Background: require('./img/profile_background.jpg'),
Pdf_Icon: require('./img/pdf_icon.png'),
Right_Half_Arrow: require('./img/right_half_arrow.png'),
searchIcon: require('./img/search_icon.png'),
Selected_Icon: require('./img/selected.png'),
Upload_Icon: require('./img/upload_icon.png'),
User: require('./img/user_image.jpg'),
User1: require('./img/user1.jpg'),
White_Forward_Arrow: require('./img/white_forward_arrow.png'),
}

export default images